trigger: none

pool:
  name: wsl-hosted-pool
  demands:
    - agent.name -equals windows-hosted-agent

variables:
  ServiceConnectionName: 'service-connection-iac'
  DeploymentDefaultLocation: 'WestEurope'

jobs:
- job:
  steps:
  - task: AzureResourceManagerTemplateDeployment@3
    inputs:
      connectedServiceName: $(ServiceConnectionName)
      location: $(DeploymentDefaultLocation)
      deploymentScope: Subscription
      csmFile: deploy/main.bicep