trigger: 
  # No parallel executions
  batch: true
  # Trigger only when pushing to 'master' and changes are applied to ./deploy/* files
  branches:
    include:
    - master
  paths:
    include:
    - deploy

pool:
  # Custom pool with self-hosted Windows agent
  name: wsl-hosted-pool
  demands:
    - agent.name -equals windows-hosted-agent

variables:
  DeploymentDefaultLocation: 'WestEurope'

jobs:
- job:
  steps:
  - task: AzureResourceManagerTemplateDeployment@3
    inputs:
      connectedServiceName: $(ServiceConnectionName)
      location: $(DeploymentDefaultLocation)
      deploymentScope: Subscription
      csmFile: deploy/main.bicep