trigger: none

pool:
  name: wsl-hosted-pool
  demands:
    - agent.name -equals wsl-hosted-agent

variables:
- name: deploymentDefaultLocation
  value: westus3
- name: EnvironmentType
  value: nonprod
- name: AZURE_ACCESS_TOKEN
  value: 'System.Security.SecureString'
- name: TenantId
  value: '604c1504-c6a3-4080-81aa-b33091104187'

jobs:
- job:
  steps:

  - task: AzurePowerShell@5
    inputs:
      azureSubscription: ''
      ScriptType: InlineScript
      Inline: |
        Connect-AzAccount -AccessToken $(AZURE_ACCESS_TOKEN) -Tenant $(TenantId)

        New-AzResourceGroupDeployment `
          -ResourceGroupName $(ResourceGroupName) `
          -TemplateFile deploy/main.bicep `
          -deploymentName $(Build.BuildNumber) `
          -TemplateParameterObject @{ environmentType = "$(EnvironmentType)" } `
          -Location $(deploymentDefaultLocation)

          pwsh: true