trigger: none

pool:
  name: wsl-hosted-pool
  demands:
    - agent.name -equals wsl-hosted-agent

jobs:
- job: helloWorldJob
  displayName: 'Building project...'
  steps:
  - script: echo Hello world!
    displayName: 'First pipeline step is:'